name: openmmlab
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - pillow=10.2.0
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.8.19
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchvision=0.18.0
  - typing_extensions=4.9.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.15.1
      - aliyun-python-sdk-kms==2.16.2
      - appdirs==1.4.4
      - asttokens==2.4.1
      - attrs==23.2.0
      - backcall==0.2.0
      - blinker==1.7.0
      - cffi==1.16.0
      - chamfer-3d==0.0.0
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==42.0.5
      - cycler==0.12.1
      - dash==2.16.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - emd==0.0.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - flask==3.0.3
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h5py==3.11.0
      - hdf5view==0.1.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - ipython==8.12.3
      - ipywidgets==8.1.2
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jmespath==0.10.0
      - joblib==1.4.0
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.4
      - mmsegmentation==1.2.2
      - model-index==0.1.11
      - munch==4.0.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nibabel==5.2.1
      - ninja==1.11.1.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - open3d==0.18.0
      - opencv-python==4.9.0.80
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.38
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.0
      - pandas==2.0.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.1
      - plotly==5.21.0
      - pooch==1.8.2
      - prettytable==3.10.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pydicom==2.4.4
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.15.0
      - pyqtgraph==0.13.3
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyvista==0.44.2
      - pyvistaqt==0.11.2
      - qtpy==2.4.1
      - referencing==0.35.0
      - requests==2.28.2
      - retrying==1.3.4
      - rich==13.4.2
      - rpds-py==0.18.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - scooby==0.10.0
      - seaborn==0.13.2
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - setuptools==60.2.0
      - shapely==2.0.4
      - six==1.16.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tenacity==8.2.3
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - threadpoolctl==3.4.0
      - tomli==2.0.1
      - torch==2.2.2
      - torchaudio==2.2.2
      - tqdm==4.65.2
      - traitlets==5.14.3
      - triton==2.2.0
      - tzdata==2024.1
      - urllib3==1.26.18
      - vtk==9.3.1
      - wandb==0.16.6
      - wcwidth==0.2.13
      - werkzeug==3.0.2
      - widgetsnbextension==4.0.10
      - yapf==0.40.2
      - zipp==3.18.1
